# Windcentrale
# Source: https://github.com/Xorfor/Domoticz-Windcentrale-Plugin/wiki/Windmills
- platform: rest
  name: De Grote Geert
  device_class: power
  scan_interval: 60
  resource: https://zep-api.windcentrale.nl/production/1/live # for .../1/... replace the '1' for the id of your windmill
  json_attributes:
    - powerProducerId
    - windSpeed
    - windDirection
    - powerAbsTot
    - powerAbsWd
    - powerRel
    - diameter
    - rpm
    - pulsating
    - kwh
    - kwhForecast
    - hoursRunThisYear
    - runPercentage
    - windSpeedForecast
    - windDirectionForecast
    - timestamp
  value_template: "{{ value_json.powerAbsWd * 2 }}" # for ... * 2 ... replace the '2' for the number of windshares you own
  unit_of_measurement: "W"
- platform: template
  sensors:
    de_grote_geert_speed:
      friendly_name: "De Grote Geert - Windsnelheid"
      value_template: '{{ states.sensor.de_grote_geert.attributes["windSpeed"] }}'
      unit_of_measurement: "Bft"

- platform: rest
  name: De Grote Geert - Energy
  device_class: power
  scan_interval: 300
  resource: https://zep-api.windcentrale.nl/production/1 # for .../1 replace the '1' for the id of your windmill
  json_attributes: 
    - response
  # below for ... (2 * 1000 * s / w) ... replace the '2' for the number of windshares you own
  value_template: >-
    {% set w = value_json["response"]["productie"]["@winddelen"] | float%}
    {% for x in value_json["response"]["productie"]["subset"] -%}
      {% if x["@period"] == "DAY" %}
        {% set s = x["@sum"] | float %}
        {{ (2 * 1000 * s / w) | round(0) }}
      {% endif %}
    {%- endfor %}
  unit_of_measurement: "Wh"

